index:
  url:                        /
  module:                     front
  action :                    index

article_view:
  url:                        /article-([0-9]+)
  module:                     front
  action:                     articleView
  varsNames:
        - id

test_controller_dont_exists:
  url:                        /test/controller
  module:                     nope
  action:                     nope

test_action_dont_exists:
  url:                        /test/action
  module:                     test
  action:                     lalala

test_execute:
  url:                        /test/execute
  module:                     test
  action:                     test
