index:
  url:                        /([0-9]*)
  module:                     front
  action :                    index
  varsNames:
        - page

article_view:
  url:                        /article-([0-9]+)
  module:                     front
  action:                     articleView
  varsNames:
        - id

contact:
  url:                        /contact
  module:                     front
  action:                     contact

test_controller_dont_exists:
  url:                        /test/controller
  module:                     nope
  action:                     nope

test_action_dont_exists:
  url:                        /test/action
  module:                     test
  action:                     lalala

test_execute:
  url:                        /test/execute
  module:                     test
  action:                     test
